### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by ulikoehler** [cwbeck/Simple-NodeJS-DNS-Server#1]
Would you mind adding a LICENSE file or something similar to this project -- otherwise no-one can use it in any project because of legal uncertanity!

Thanks in advance!

**Comment by cwbeck** [comment]
Hi,

Please fork, add a license from one of my other projects, eg.
https://github.com/cwbeck/nanophp/blob/master/LICENCE and do a pull request
- I will merge it in. I honestly didn't realize it didn't have one.

Thanks,

Chris

On Sun, Dec 23, 2012 at 5:37 PM, Uli Köhler notifications@github.comwrote:

> Would you mind adding a LICENSE file or something similar to this project
> -- otherwise no-one can use it in any project because of legal uncertanity!
> 
> Thanks in advance!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/cwbeck/Simple-NodeJS-DNS-Server/issues/1.

## 

Christopher Beck

**Comment by ulikoehler** [comment]
Hi Chris,
thanks for your quick reply! I submitted the pull request (probably not the last one...), so I think we can close this issue.

Best regards,
Uli
